version: "2"

services:
  nginx-react:
    container_name: techhub-nginx-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt